/// Flutter icons MyCustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyCustomIcons
///      fonts:
///       - asset: fonts/MyCustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyCustomIcons {
  MyCustomIcons._();

  static const _kFontFam = 'MyCustomIcons';
  static const _kFontPkg = null;

  static const IconData dice_3 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_marker_check = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_marker_distance = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
